env:
  es6: true
  node: true
extends:
  - eslint:recommended
  - plugin:prettier/recommended
parserOptions:
  sourceType: module
  ecmaVersion: 2018
rules:
  no-case-declarations: 0
  linebreak-style:
    - error
    - unix
